## Lab Assignment 10: <br>
### Student Name: Daniel Beckley
### Student ID: 8846774

This assignment targets to assure that the students understood basic IR concepts.<br>

**Part 1: Implementing an IR System (10/16)**<br>

Consider a collection of 1000 documents and a set of 10 queries. Implement an IR system based on the Vector Space Model (VSM) using TF-IDF weighting.<br>

Dataset:<br>

- 1000 documents (text content for each document)
- 10 sample queries <br>
IR System:<br>

Implement TF-IDF calculation for document-term matrix construction. <br>
Develop a cosine similarity-based retrieval system to rank documents for each query. <br>
Rank the top 10 documents for each query using the IR system. <br>
Evaluation: <br>

Compute Precision at k (P@k) for k=5, k=6, and k=10 for each query.<br>
Calculate Mean Average Precision (MAP) across all queries. <br>
Calculate the Mean Reciprocal Rank (MRR) across all queries.(3) <br><br>
**Part 2: Assessing Inter-Annotator Agreement (6/16)**<br>

Given the relevance assessments by three different annotators for a set of documents:<br>

Annotator 1,2 and 3 relevance assessments<br>

You are expected to: <br>

Compute pairwise Cohen's Kappa values for the annotators' relevance assessments.<br>
Discuss the observed agreement levels among annotators.<br>
Explain how to improve the kappa value if we are not satisfied with the kappa.<br>
Hint: Check Kappa Measure Last Slide Week 11


----------------------------------------------------------------------------------------
- Part 1

In [115]:
documents = [
    "Machine learning is transforming various industries.",
    "Natural language processing helps in text analysis.",
    "AI algorithms can improve decision-making processes.",
    "Data science involves extracting insights from data.",
    "Robotics is a field combining hardware and software.",
    "Deep learning models require large amounts of data.",
    "Blockchain technology secures digital transactions.",
    "Cloud computing offers scalable computing power.",
    "Virtual reality provides immersive experiences.",
    "Augmented reality enhances real-world environments.",
    "Internet of Things connects devices for data exchange.",
    "Biometric authentication ensures secure access.",
    "Quantum computing promises faster computations.",
    "Cybersecurity protects against digital threats.",
    "Ethical considerations in AI development are crucial.",
    "Healthcare benefits from AI-driven diagnostics.",
    "E-commerce relies on personalized recommendation systems.",
    "Autonomous vehicles revolutionize transportation.",
    "Smart cities utilize IoT for efficient operations.",
    "Social media analysis aids in understanding trends.",
    "Predictive analytics anticipates future outcomes.",
    "Remote work trends increase reliance on digital tools.",
    "Energy efficiency through smart grids is vital.",
    "Fintech innovations reshape financial services.",
    "Data privacy concerns arise in the era of big data.",
    "Artificial general intelligence remains a challenge.",
    "Human-computer interaction shapes user experiences.",
    "Big data analytics drives informed decision-making.",
    "Climate change predictions benefit from AI models.",
    "Bioinformatics applies computational techniques to biology.",
    "Robotic process automation streamlines workflows.",
    "Industry 4.0 integrates AI with manufacturing.",
    "Sentiment analysis detects emotions in text data.",
    "Reinforcement learning powers autonomous agents.",
    "Data visualization simplifies complex information.",
    "Edge computing reduces latency in data processing.",
    "Smart farming optimizes agricultural practices.",
    "AI in education enhances personalized learning.",
    "Natural disaster predictions leverage machine learning.",
    "Media recommendation systems personalize content.",
    "Speech recognition enables hands-free interactions.",
    "Genetic algorithms mimic natural selection.",
    "Neural networks simulate the human brain.",
    "Behavioral analytics uncovers patterns in behavior.",
    "Spatial analysis benefits from geospatial data.",
    "Explainable AI improves transparency in models.",
    "AI ethics guide responsible technology development.",
    "Prescriptive analytics offers actionable insights.",
    "Supply chain optimization employs predictive models.",
    "Emotion AI detects emotions in facial expressions.",
    "Distributed ledger technology ensures secure transactions.",
    "Biological data analysis aids in medical research.",
    "Smart grid technology enhances energy distribution.",
    "AI-powered chatbots automate customer support.",
    "Machine translation breaks language barriers.",
    "Personalized medicine tailors treatments to individuals.",
    "Data-driven marketing optimizes customer engagement.",
    "Smart home devices enhance living experiences.",
    "Time series forecasting predicts future trends.",
    "AI-driven creativity challenges human capabilities.",
    "Intelligent document processing automates data extraction.",
    "Graph analytics explores relationships in networks.",
    "Adversarial attacks pose challenges to AI security.",
    "Predictive maintenance minimizes equipment downtime.",
    "Spatial reasoning enhances AI navigation systems.",
    "Privacy-preserving techniques protect sensitive data.",
    "Automated decision-making raises ethical concerns.",
    "Behavioral biometrics verifies user identities.",
    "Explainable recommendations increase user trust.",
    "Quantum machine learning explores quantum states.",
    "Internet censorship detection uses AI techniques.",
    "Smart wearables monitor health and fitness.",
    "Intelligent tutoring systems adapt to student needs.",
    "Graph neural networks model complex relationships.",
    "AI in sports analytics improves performance analysis.",
    "Facial recognition technology raises privacy debates.",
    "Digital twin technology replicates physical systems.",
    "Emotion detection in video content aids analysis.",
    "Neuromorphic computing mimics brain structure.",
    "Robotic surgery enhances precision in operations.",
    "AI-powered language translation assists global communication.",
    "Automated content moderation filters online content.",
    "Network anomaly detection identifies security threats.",
    "Predictive policing uses data to prevent crime.",
    "Quantum cryptography ensures secure communications.",
    "AI-generated art challenges traditional creativity.",
    "Ethical considerations in autonomous vehicles are debated.",
    "Adaptive learning systems personalize educational content.",
    "Biomedical image analysis aids in disease diagnosis.",
    "Explainable computer vision interprets image features.",
    "AI-driven personalization enhances user experiences.",
    "Conversational AI improves human-like interactions.",
    "Federated learning protects individual data privacy.",
    "Human-centered AI design prioritizes user needs.",
    "Quantum annealing solves optimization problems.",
    "Behavior-based authentication enhances security.",
    "AI in music composition transforms creative processes.",
    "Semantic search improves information retrieval.",
    "Recommender systems optimize user preferences.",
    "Information Retrieval systems are outdated without neural networks"
]
print(len(documents))

100


In [116]:
queries = [
    "What are the impacts of AI on healthcare?",
    "How does machine learning improve financial services?",
    "What is the role of AI in autonomous vehicles?",
    "Explain the applications of natural language processing.",
    "How does robotics benefit from AI integration?",
    "What are the challenges in implementing AI in education?",
    "How does data science contribute to climate change predictions?",
    "What are the ethical considerations in AI development?",
    "Explain the significance of AI in smart cities.",
    "How does AI enhance cybersecurity measures?"
]
print(len(queries))

10


In [117]:
ground_truth =[[3, 74, 38, 92, 71, 72, 98, 48, 18, 100], 
                [12, 26, 52, 54, 21, 63, 64, 45, 14, 83],
                [58, 77, 62, 31, 6, 61, 36, 96, 85, 18], 
                [99, 62, 98, 34, 63, 79, 43, 31, 3, 16],
                [8, 88, 73, 82, 37, 25, 34, 87, 66, 58], 
                [90, 40, 84, 64, 34, 2, 73, 23, 59, 89],
                [80, 10, 86, 21, 68, 37, 83, 57, 6, 98],
                [22, 3, 2, 44, 56, 80, 50, 63, 87, 13],
                [1, 18, 22, 44, 99, 72, 24, 95, 10, 87],
                [31, 10, 56, 50, 75, 4, 18, 85, 84, 74]
                           ]
print(len(ground_truth))


10


In [118]:
## TODO: Implement your solution for part 1

### 

In [119]:
from sklearn.feature_extraction.text import TfidfVectorizer
from nltk.tokenize import word_tokenize

### Tokenize Documents

In [120]:
tokenized_documents = [word_tokenize(document) for document in documents]
tokenized_documents

[['Machine', 'learning', 'is', 'transforming', 'various', 'industries', '.'],
 ['Natural', 'language', 'processing', 'helps', 'in', 'text', 'analysis', '.'],
 ['AI', 'algorithms', 'can', 'improve', 'decision-making', 'processes', '.'],
 ['Data',
  'science',
  'involves',
  'extracting',
  'insights',
  'from',
  'data',
  '.'],
 ['Robotics',
  'is',
  'a',
  'field',
  'combining',
  'hardware',
  'and',
  'software',
  '.'],
 ['Deep',
  'learning',
  'models',
  'require',
  'large',
  'amounts',
  'of',
  'data',
  '.'],
 ['Blockchain', 'technology', 'secures', 'digital', 'transactions', '.'],
 ['Cloud', 'computing', 'offers', 'scalable', 'computing', 'power', '.'],
 ['Virtual', 'reality', 'provides', 'immersive', 'experiences', '.'],
 ['Augmented', 'reality', 'enhances', 'real-world', 'environments', '.'],
 ['Internet',
  'of',
  'Things',
  'connects',
  'devices',
  'for',
  'data',
  'exchange',
  '.'],
 ['Biometric', 'authentication', 'ensures', 'secure', 'access', '.'],
 ['Qua

### Remove Stop words

In [121]:
from nltk.corpus import stopwords
english_stopwords = stopwords.words('english')
cleaned_data = [[word.lower() for word in document if word.lower() not in english_stopwords] for document in tokenized_documents]
cleaned_data

[['machine', 'learning', 'transforming', 'various', 'industries', '.'],
 ['natural', 'language', 'processing', 'helps', 'text', 'analysis', '.'],
 ['ai', 'algorithms', 'improve', 'decision-making', 'processes', '.'],
 ['data', 'science', 'involves', 'extracting', 'insights', 'data', '.'],
 ['robotics', 'field', 'combining', 'hardware', 'software', '.'],
 ['deep', 'learning', 'models', 'require', 'large', 'amounts', 'data', '.'],
 ['blockchain', 'technology', 'secures', 'digital', 'transactions', '.'],
 ['cloud', 'computing', 'offers', 'scalable', 'computing', 'power', '.'],
 ['virtual', 'reality', 'provides', 'immersive', 'experiences', '.'],
 ['augmented', 'reality', 'enhances', 'real-world', 'environments', '.'],
 ['internet', 'things', 'connects', 'devices', 'data', 'exchange', '.'],
 ['biometric', 'authentication', 'ensures', 'secure', 'access', '.'],
 ['quantum', 'computing', 'promises', 'faster', 'computations', '.'],
 ['cybersecurity', 'protects', 'digital', 'threats', '.'],
 ['

### Join Tokens

In [122]:
cleaned_sentences = [' '.join(document) for document in cleaned_data]
cleaned_sentences

['machine learning transforming various industries .',
 'natural language processing helps text analysis .',
 'ai algorithms improve decision-making processes .',
 'data science involves extracting insights data .',
 'robotics field combining hardware software .',
 'deep learning models require large amounts data .',
 'blockchain technology secures digital transactions .',
 'cloud computing offers scalable computing power .',
 'virtual reality provides immersive experiences .',
 'augmented reality enhances real-world environments .',
 'internet things connects devices data exchange .',
 'biometric authentication ensures secure access .',
 'quantum computing promises faster computations .',
 'cybersecurity protects digital threats .',
 'ethical considerations ai development crucial .',
 'healthcare benefits ai-driven diagnostics .',
 'e-commerce relies personalized recommendation systems .',
 'autonomous vehicles revolutionize transportation .',
 'smart cities utilize iot efficient oper

### TFIDF Matrix

In [123]:
tfidf_vectorizer = TfidfVectorizer()
tfidf_matrix = tfidf_vectorizer.fit_transform(cleaned_sentences)
print(tfidf_matrix)

  (0, 163)	0.49120372384880856
  (0, 327)	0.49120372384880856
  (0, 312)	0.49120372384880856
  (0, 181)	0.34109961564339564
  (0, 186)	0.3997596243233148
  (1, 11)	0.3259493911700577
  (1, 305)	0.43071911294080617
  (1, 151)	0.4693864999729862
  (1, 242)	0.4032841652344177
  (1, 178)	0.4032841652344177
  (1, 202)	0.4032841652344177
  (2, 241)	0.43630037870457955
  (2, 188)	0.4085099284682032
  (2, 81)	0.4085099284682032
  (2, 158)	0.47546881841107386
  (2, 9)	0.43630037870457955
  (2, 7)	0.24382911739385216
  (3, 168)	0.40332998980704693
  (3, 123)	0.4395385451021021
  (3, 176)	0.4395385451021021
  (3, 273)	0.4395385451021021
  (3, 78)	0.5076834854816823
  (4, 289)	0.4472135954999579
  (4, 148)	0.4472135954999579
  (4, 56)	0.4472135954999579
  :	:
  (95, 23)	0.4623932891322133
  (95, 111)	0.3619774719865355
  (96, 71)	0.4425900318406722
  (96, 313)	0.4425900318406722
  (96, 61)	0.4425900318406722
  (96, 201)	0.4425900318406722
  (96, 241)	0.40613009944220513
  (96, 7)	0.226968273527723

### Preprocess Query (similar to documents)

In [124]:
def preprocess_query(query):
    query_tokens = word_tokenize(query)
    query_cleaned = [word.lower() for word in query_tokens if word.lower() not in english_stopwords]
    query_cleaned_combined = ' '.join(query_cleaned)
    return query_cleaned_combined

### Calculate Cosine SImilarities

Documents are indexed from 1 to 100 for this presentation.

In [125]:
from sklearn.metrics.pairwise import cosine_similarity
import numpy as np

def get_top_10_similar_docs(query, tfidf_matrix):
    # Preprocess the query
    query_cleaned = preprocess_query(query)

    # Transform the query into a TF-IDF vector
    query_tfidf = tfidf_vectorizer.transform([query_cleaned])

    # Calculate the cosine similarity between the query vector and all document vectors
    cosine_similarities = cosine_similarity(query_tfidf, tfidf_matrix)

    # Get the indices of the 10 most similar documents

    top_indices = np.argsort(cosine_similarities, axis=1)[0, -10:][::-1]
    
    # Adjust indices to start from 1 instead of 0
    top_indices_adjusted = top_indices + 1

    return top_indices_adjusted

In [126]:
top_10_similar_docs = [get_top_10_similar_docs(query, tfidf_matrix) for query in queries]
top_10_similar_docs

[array([16, 38, 32, 46, 91, 15, 75, 65, 60, 92], dtype=int64),
 array([24,  1, 39, 70,  3, 55, 38, 34, 93, 88], dtype=int64),
 array([18, 87, 34, 38, 32, 46, 91, 15, 16, 75], dtype=int64),
 array([ 2, 55, 42, 39, 36, 61, 81, 28, 29, 30], dtype=int64),
 array([29,  5, 38, 32, 46, 91, 15, 16, 75, 65], dtype=int64),
 array([38, 60, 63, 86, 32, 46, 91, 15, 16, 75], dtype=int64),
 array([29,  4, 39, 25, 45, 35, 93, 33, 52, 57], dtype=int64),
 array([15, 87, 47, 67, 38, 32, 46, 91, 16, 75], dtype=int64),
 array([19, 37, 23, 53, 72, 58, 38, 32, 46, 91], dtype=int64),
 array([14, 58, 38, 32, 46, 91, 15, 16, 75, 65], dtype=int64)]

### Precision at K

In [127]:
def precision_at_k(ground_truth, retrieved_docs, k=10):
    precisions = []
    for i in range(len(ground_truth)):
        correct_predictions = set(ground_truth[i])
        
        top_k_predictions = set(retrieved_docs[i][:k])
        
        precision = len(correct_predictions.intersection(top_k_predictions)) / k
        
        precisions.append(precision)
    return precisions


Precision at k = 5

In [128]:
precision_at_k(ground_truth, top_10_similar_docs, k=5)

[0.2, 0.0, 0.2, 0.0, 0.0, 0.0, 0.0, 0.2, 0.2, 0.0]

Precision at k = 6

In [129]:
precision_at_k(ground_truth, top_10_similar_docs, k=6)

[0.16666666666666666,
 0.0,
 0.16666666666666666,
 0.0,
 0.0,
 0.0,
 0.0,
 0.16666666666666666,
 0.16666666666666666,
 0.0]

Precision at k = 10

In [130]:
precision_at_k(ground_truth, top_10_similar_docs, k=10)

[0.2, 0.0, 0.1, 0.0, 0.0, 0.0, 0.1, 0.1, 0.1, 0.1]

### Average Precisions

In [131]:
import numpy as np

def calculate_average_precision(retrieved_documents, relevant_documents):
    # Find the indices (k values) where retrieved documents are relevant
    k_values_ap = [i + 1 for i in range(len(retrieved_documents)) if retrieved_documents[i] in relevant_documents]
    # print(f'Indices of relevant and retrieved documents are: {k_values_ap}')

    # Calculate Precision at k for each relevant and retrieved document
    precision_k_lists_ap = []
    for k in k_values_ap:
        # Retrieve the top k documents
        retrieved_k_documents = retrieved_documents[:k]
        # Calculate the number of True Positives (relevant documents in the top k)
        TP_k = len(set(relevant_documents) & set(retrieved_k_documents))
        # Calculate Precision at k
        precision_k = TP_k / len(retrieved_k_documents)
        precision_k_lists_ap.append(precision_k)

    # print(precision_k_lists_ap)

    # If precision_k_lists_ap is empty, set average_precision to 0, otherwise calculate the mean
    if not precision_k_lists_ap:  # Check if the list is empty
        average_precision = 0
    else:
        average_precision = np.nanmean(precision_k_lists_ap) * 100  # Use nanmean to handle NaN values

    # print(f'Average Precision is {average_precision}%')

    return average_precision


In [132]:
calculate_average_precision(top_10_similar_docs[0], ground_truth[0])

35.0

In [133]:
average_precisions = [calculate_average_precision(retrieved_docs, relevant_docs) for retrieved_docs, relevant_docs in zip(top_10_similar_docs, ground_truth)]
average_precisions

[35.0, 0, 100.0, 0, 0, 0, 10.0, 50.0, 20.0, 11.11111111111111]

### Mean Average Precision

In [134]:
import numpy as np

def calculate_map(ap_scores):

    map_score = np.mean(ap_scores)

    print(f'Mean Average Precision (MAP) is: {map_score}%')

    return map_score


In [135]:
map_score = calculate_map(average_precisions)

Mean Average Precision (MAP) is: 22.61111111111111%


### Mean Reciprocal Rank

In [136]:
def calculate_mrr(list_of_retrieved_documents, list_of_relevant_documents):
    reciprocal_ranks = []

    for retrieved_docs, relevant_docs in zip(list_of_retrieved_documents, list_of_relevant_documents):
        rr = 0
        for rank, doc in enumerate(retrieved_docs, start=1):
            if doc in relevant_docs:
                rr = 1 / rank
                break
        reciprocal_ranks.append(rr)

    mrr = sum(reciprocal_ranks) / len(reciprocal_ranks)
    print(f'Mean Reciprocal Rank (MRR) is: {mrr}')

    return mrr

In [137]:
calculate_mrr(top_10_similar_docs, ground_truth)

Mean Reciprocal Rank (MRR) is: 0.24111111111111114


0.24111111111111114

-------------------------------------------------------------------
## - Part 2

In [138]:
# 0 is not relevant, 1 is relevant
annotator1_relevance = [1, 0, 1, 0, 1, 1, 0, 0, 1, 0]  
annotator2_relevance = [1, 1, 1, 0, 1, 0, 0, 1, 1, 1]  
annotator3_relevance = [1, 0, 0, 0, 1, 0, 0, 1, 1, 0]  

In [139]:
## TODO: Implement your solution for part 2

### Pairwise Cohen's Kappa Values

In [140]:
from sklearn.metrics import confusion_matrix

def calculate_kappa_score(annotator1, annotator2):
    confusion_matrix_res = confusion_matrix(annotator2, annotator1)
    total_docs = len(annotator1)
    
    # Calculate the probability of agreeing
    prob_agreeing = (confusion_matrix_res[0, 0] + confusion_matrix_res[1, 1]) / total_docs
    
    # Calculate the probability of both annotators marking a document as relevant by chance
    prob_relevant = (sum(confusion_matrix_res[:, 1]) / total_docs) * (sum(confusion_matrix_res[1, :]) / total_docs)
    
    # Calculate the probability of both annotators marking a document as not relevant by chance
    prob_not_relevant = (sum(confusion_matrix_res[:, 0]) / total_docs) * (sum(confusion_matrix_res[0, :]) / total_docs)
    
    # Calculate the total probability of chance agreement
    prob_chance = prob_relevant + prob_not_relevant
    
    # Calculate kappa score
    kappa_score = (prob_agreeing - prob_chance) / (1 - prob_chance)
    
    return kappa_score



In [141]:
kappa_score_1 = calculate_kappa_score(annotator1_relevance, annotator2_relevance)
kappa_score_1

0.19999999999999996

In [142]:
kappa_score_2 = calculate_kappa_score(annotator1_relevance, annotator3_relevance)
kappa_score_2

0.3999999999999999

In [143]:
kappa_score_3 = calculate_kappa_score(annotator2_relevance, annotator3_relevance)
kappa_score_3

0.4444444444444444

### Discussion

For annotator 1 and annotator 2, a kappa score of 0.2 shows a slight agreement beyond what would be expected by chance alone on the relevance assessments. The low kappa value suggests that these two annotators have relatively divergent views on what constitutes relevance in the context of their assessments.

For annotator 1 and annotator 3, a kappa score of 0.4 shows a fair agreement suggesting that annotator 1 and annotator 3 have more similar criteria or interpretations for relevance, leading to more consistent judgments compared to the first pair.

For annotator 2 and annotator 3, a kappa score of 0.44 shows a moderate agreement, slightly higher than the agreement between annotator 1 and annotator 3. It suggests that annotator 2 and annotator 3 share relatively similar assessment criteria, resulting in a slightly more consistent judgment.

### To Improve Kappa Value

More annotators are needed or replace one of the annotators.

Ensure that the guidelines for making relevance assessments are clear.

Conduct training sessions where annotators can practice making assessments and receive feedback.

Consider whether the task itself may be too subjective or if the categories are too broad or overlapping.

### Average Pairwise Kappa

In [144]:
average_pairwise_kappa = (kappa_score_1 + kappa_score_2 + kappa_score_3) / 3
average_pairwise_kappa

0.3481481481481481