In [52]:
import numpy as np

## Part A

1. Create an array that starts from the integer 1, ends at 20, incremented by 3. 

In [53]:
arr = np.arange(1, 20, 3)
arr

array([ 1,  4,  7, 10, 13, 16, 19])

2. Create a new array of shape 3 with random numbers between 0 and 1. 

In [54]:
arr2 = np.random.rand(3)
arr2

array([0.5265462 , 0.84928327, 0.16045902])

3. Create a 2 D array [[10,20,45],[30,12,16],[42,17,56]] and perform the following operations:


In [55]:
my_2d_array = np.array([[10, 20, 45], [30, 12, 16], [42, 17, 56]])
my_2d_array

array([[10, 20, 45],
       [30, 12, 16],
       [42, 17, 56]])

- Slice the 2D array to get the first two rows

In [56]:
first_two_rows = my_2d_array[:2]
first_two_rows

array([[10, 20, 45],
       [30, 12, 16]])

- Slice the 2D array to get the last two rows

In [57]:
last_two_rows = my_2d_array[-2:]
print(last_two_rows)

[[30 12 16]
 [42 17 56]]


4. Create two 2x2 arrays and demonstrate how you can stack the elements vertically, horizontally, and split the arrays into smaller arrays. 

In [58]:
my_first_2by2_array = np.array([[2, 0], [3, 7]])
my_second_2by2_array = np.array([[8, 6], [5, 9]])
my_first_2by2_array, my_second_2by2_array

(array([[2, 0],
        [3, 7]]),
 array([[8, 6],
        [5, 9]]))

-  Vertical Stacking

In [59]:
vertical_stack = np.vstack((my_first_2by2_array, my_second_2by2_array))
vertical_stack

array([[2, 0],
       [3, 7],
       [8, 6],
       [5, 9]])

- Horizontal Stacking

In [60]:
horizontal_stack = np.hstack((my_first_2by2_array, my_second_2by2_array))
horizontal_stack

array([[2, 0, 8, 6],
       [3, 7, 5, 9]])

- Split the arrays

In [61]:
np.split(my_first_2by2_array, 1)

[array([[2, 0],
        [3, 7]])]

In [62]:
np.split(my_first_2by2_array, 2)

[array([[2, 0]]), array([[3, 7]])]

In [63]:
np.split(my_first_2by2_array, 2, 1)

[array([[2],
        [3]]),
 array([[0],
        [7]])]

In [64]:
np.split(my_second_2by2_array, 2, 0)


[array([[8, 6]]), array([[5, 9]])]

In [65]:
np.split(my_first_2by2_array, 2, 0)

[array([[2, 0]]), array([[3, 7]])]

In [66]:
np.split(my_second_2by2_array, (1, 2))

[array([[8, 6]]), array([[5, 9]]), array([], shape=(0, 2), dtype=int32)]

5. Create two matrices 𝑋= ([[5,7,2],[4,5,6],[7,4 ,2]]), 𝑌= ([[4,2],[6,2],[4,2]]), 


In [67]:
matrix_x = np.array([[5,7,2],[4,5,6],[7,4 ,2]])
print('matrix_x \n', matrix_x)

matrix_x 
 [[5 7 2]
 [4 5 6]
 [7 4 2]]


In [68]:
matrix_y = np.array([[4, 2],[6, 2],[4, 2]])
print('matrix_y \n', matrix_y)

matrix_y 
 [[4 2]
 [6 2]
 [4 2]]


- Is it possible to multiply these matrices? 

For two matrices to be multiplied, the number of columns in the first matrix must be equal to the number of rows in the second matrix. This principle is actually called the `conformability of matrices`



In [69]:
print(matrix_x.shape)
print(matrix_y.shape)

(3, 3)
(3, 2)


As we can see above, the number of `columns` in `matrix_x` is `3` and the number of `rows` in `matrix_y` is `3`. So, we can say that `matrix_x` and `matrix_y` are `conformable for multiplication`.

In [70]:
np.dot(matrix_x, matrix_y)

array([[70, 28],
       [70, 30],
       [60, 26]])

But if the two matrices were not `conformable for multiplication`, we would have an error.

In [71]:
test_a = np.array([[1, 3]])
test_b = np.array([[4, 5], [6, 8], [0, 7]])

print(test_a.shape)
print(test_b.shape)

(1, 2)
(3, 2)


In [72]:
np.dot(test_a, test_b)

ValueError: shapes (1,2) and (3,2) not aligned: 2 (dim 1) != 3 (dim 0)

6. Create two arrays, 𝑥 = ([2,−1,−8]) 𝑦 = ([3,1,−2])

In [73]:
vector_x = np.array([2, -1, -8])
vector_y = np.array([3, 1, -2])

print('vector_x\n', vector_x)
print('==========')
print('vector_y\n', vector_y)

vector_x
 [ 2 -1 -8]
vector_y
 [ 3  1 -2]


- Find the Shape, Number of dimensions of vector x. 

In [74]:
print('shape \n', vector_x.shape)
print('dimensions \n', vector_x.ndim)


shape 
 (3,)
dimensions 
 1


- Reshape the vector x to a matrix of size (3,1) and determine the number of dimensions after reshaping y to a matrix of (3,1). 

In [75]:
print("reshaped vector_x \n", vector_x.reshape(3, 1))

reshaped vector_x 
 [[ 2]
 [-1]
 [-8]]


In [76]:
vector_y = vector_y.reshape(3, 1)
print("reshaped vector_y \n", vector_y)
print("reshaped vector_y new dimensions \n", vector_y.ndim)

reshaped vector_y 
 [[ 3]
 [ 1]
 [-2]]
reshaped vector_y new dimensions 
 2


7. How does broadcasting work?

Whenever we want to perform arithmetic operations between a vector and a number(scalar), or between vectors of different sizes, numpy does what we call `broadcasting` by using the number for each of the cells in our vector.

In [77]:
# For example
data = np.array([1.0, 2.0])
data * 1.6

array([1.6, 3.2])

In the above, numpy knows that we want to multiply all the cells by `1.6` and it `broadcasts` this value across all our cells.

- Demonstrate the subtraction, multiplication by considering a 3 x 3 matrix. 

In [78]:
data = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
data


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [79]:
data - 5

array([[-4, -3, -2],
       [-1,  0,  1],
       [ 2,  3,  4]])

In [80]:
data * 5

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

Note: The dimensions of your array must be compatible, for example, when the dimensions of both arrays are equal or when one of them is 1. If the dimensions are not compatible, you will get a `ValueError`.

## Part B - Linear Equations

- Determine the singularity of the system of equations, comment on the expected solution of the system. Solve the system of equations if possible. Justify the reason why you believe the system can or cannot be solved using NumPy functions. 

1 
- 1. 4x + y - 2z = 10 
- 2. 2x - 3y + 2z = -4 
- 3. x + 2y + 3z = 6 

In [81]:
lhs = np.array([[4, 1, -2], [2, -3, 2], [1, 2, 3]])
rhs = np.array([10, -4, 6])

Singularity of equations is whether the the equation is singular or not singular.

To determine whether a system of linear equations is singular vs non-singular, we will use **The Determinant**

- If the determinant of the matrix of the system is equal to zero → Singular System

- If the determinant of the matrix of the system is not equal to zero → Non-Singular System


Another way to look at this is if one of the equations in the systemis linearly dependent on another equation, then the system of singulars will be singular, cannot be solved.

In [82]:
np.linalg.det(lhs)

-70.00000000000003

From the above, our determinant is not zero, which mean the system is Non-singular and can be solved

In [83]:
sol = np.linalg.solve(lhs, rhs)
print(sol)

[ 1.8  2.4 -0.2]


We can also confirm if our solution is correct

In [84]:
np.allclose(np.dot(lhs, sol), rhs)

True

2 
-   1. 2x - y + 3z + 4w = 10 
-   2. 4x - 2y + 6z + 8w = 20 
-   3. 3x + y - 2z + 2w = 3 
-   4. x + 3y - 4z + w = -1 

In [85]:
lhs = np.array([[2, -1, 3, 4], [4, -2, 6, 8], [3, 1, -2, 2], [1, 3, -4, 1]])
rhs = np.array([10, 20, 3, -1])

In [86]:
#find the determinant
np.linalg.det(lhs)

0.0

Since the determinat of this matrix is `0`, then this system of linear equations is `singular` and cannot be solved.

If we try to solve it, we get an error

In [87]:
sol = np.linalg.solve(lhs, rhs)

LinAlgError: Singular matrix

We could have also seen that the second equation in this system depends on equation one, since it is just equation one multiplied by 2.